version: 2
jobs:
  build:
    working_directory: ~/docker-hunspell-wasm
    docker:
      - image: buildpack-deps:trusty
    environment:
      - ARTIFACT_DIR: /artifacts
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Init submodules
          command: |
             git submodule update --init --recursive
             mkdir -p /artifacts/out
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build wasm dict 1.6.1
          command: |
            BRANCH=v1.6.1
            TARGET=wasm
            # Build docker image, specify commit sha of hunspell
            docker build -t hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM --build-arg BRANCH=$BRANCH --build-arg TARGET=$TARGET .
            # Run built docker image, specify container name same as image name
            docker run --name hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM -t hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM /bin/bash -l -c "./build.sh -o /out/$BRANCH/$TARGET/hunspell.js -s WASM=1"
            # Copy build output
            docker cp hunspell-dict-wasm_0.1.$CIRCLE_BUILD_NUM:/out $ARTIFACT_DIR/
      - run:
          name: Build asmjs dict 1.6.1
          command: |
            BRANCH=v1.6.1
            TARGET=asm
            ## disable asm.js output
            # Build docker image, specify commit sha of hunspell
            #docker build -t hunspell-dict-asm_0.1.$CIRCLE_BUILD_NUM --build-arg BRANCH=$BRANCH --build-arg TARGET=$TARGET .
            # Run built docker image, specify container name same as image name
            #docker run --name hunspell-dict-asm_0.1.$CIRCLE_BUILD_NUM -t hunspell-dict-asm_0.1.$CIRCLE_BUILD_NUM /bin/bash -l -c "./build.sh -o /out/$BRANCH/$TARGET/hunspell.js"
            # Copy build output
            #docker cp hunspell-dict-asm_0.1.$CIRCLE_BUILD_NUM:/out $ARTIFACT_DIR/
      - run:
          working_directory: /artifacts
          name: Copy artifacts
          command: |
            # File copied from docker container has root access only, modify permission
            sudo chmod -R go+wr $ARTIFACT_DIR
            # Echo sha1
            find ./out -type f -exec sha1sum {} \;
            # Generate archive for convinience
            tar -zcvf ./hunspell-asm-$CIRCLE_BUILD_NUM-$CIRCLE_SHA1.tar.gz out
      - store_artifacts:
          path: /artifacts