version: 2
jobs:
  build:
    working_directory: ~/docker-hunspell-bdict-wasm
    docker:
      - image: buildpack-deps:trusty
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Init submodules
          command: |
             git submodule update --init --recursive
             cd ./hunspell && git show --summary
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build wasm
          command: |
            # Build docker image, specify commit sha of hunspell
            docker build -t hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM .
            # Run built docker image, specify container name same as image name
            docker run --name hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM -t hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM
      - run:
          name: Copy artifacts
          command: |
            HUNSPELL_BDICT_SHA=$(git rev-parse --verify HEAD)
            ARTIFACT_DIR=~/docker-hunspell-bdict-wasm/artifacts
            docker cp hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM:/out $ARTIFACT_DIR
            # File copied from docker container has root access only, modify permission
            sudo chmod -R go+wr artifacts
            # Echo sha1
            find artifacts -type f -exec sha1sum {} \;
            # Generate archive for convinience
            tar -zcvf ./hunspell-bdict-wasm_$CIRCLE_BUILD_NUM-$HUNSPELL_BDICT_SHA.tar.gz artifacts
            cp *.tar.gz $ARTIFACT_DIR
      - store_artifacts:
          path: ~/docker-hunspell-bdict-wasm/artifacts