version: 2
jobs:
  build:
    working_directory: ~/docker-hunspell-bdict-wasm
    docker:
      - image: buildpack-deps:trusty
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build wasm
          command: |
            # Build docker image, specify commit sha of hunspell
            docker build --build-arg BUILD_SHA=e86aab1345872d7de469a3ebaa294241f8de8a50 -t hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM .
            # Run built docker image, specify container name same as image name
            docker run --name hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM -t hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM
      - run:
          name: Copy artifacts
          command: |
            ARTIFACT_DIR=~/docker-hunspell-bdict-wasm/artifacts
            mkdir $ARTIFACT_DIR
            docker cp hunspell-bdict-wasm_0.1.$CIRCLE_BUILD_NUM:/out $ARTIFACT_DIR
      - store_artifacts:
          path: ~/docker-hunspell-bdict-wasm/artifacts